### ISSUE TITLE
BindDataObjectsWithSparql() does not return NEW DataObjects...

### ISSUE THREAD

**Issue by hornms** [BrightstarDB/BrightstarDB#106]
When I execute the BindDataObjectsWithSparql() function with a simple SPARQL query, it fails to return any objects unless the Store is saved.  Since the Store tracks the DataObjects, why does this function not return the IsNew objects?  Is this by design or a bug?

If this is by design, then is there a problem with performing SaveChanges() after every object gets created?

Thanks
Mike

            string sLocation = @"C:\Users\mike\Desktop\";
            string sName = @"DBTest";
            string connectionString = string.Format(@"Type=embedded;storesDirectory={0};StoreName={1};", sLocation, sName);

            oContext = BrightstarService.GetDataObjectContext(connectionString);
            oStore = oContext.CreateStore(sName, persistenceType: BrightstarDB.Storage.PersistenceType.Rewrite);
            oClient = BrightstarService.GetClient(connectionString);

            BrightstarDB.Client.IDataObject oDOType = null;
            BrightstarDB.Client.IDataObject oDO1 = null;

            string sBrightstarType = @"http://www.w3.org/1999/02/22-rdf-syntax-ns#type";
            string sType = @"http://www.mike.com/Type1";
            oDOType = oStore.GetDataObject(sType);
            oDO1 = oStore.MakeNewDataObject();
            oDO1.SetType(oDOType);

            oDO1.SetProperty(@"http://www.mike.com/Prop1", @"Mike1");

            // QUESTION:  If this is not performed, then the SPARQL will return ZERO objects?????
            oStore.SaveChanges();

            string sSPARQL = String.Format(@"SELECT ?x
WHERE {{
?x a <{2}> .
}}", oDO1.Identity, sBrightstarType, sType);

            List<BrightstarDB.Client.IDataObject> oResults = oStore.BindDataObjectsWithSparql(sSPARQL).ToList<BrightstarDB.Client.IDataObject>();

            // This fails if the Store was not Saved??????
            BrightstarDB.Client.IDataObject oDO1a = oResults[0];

**Comment by kal** [comment]
This was a while ago, but I think the docs still need updating...
