### ISSUE TITLE
Windows Phone 8.1 (WinRT) NuGet Support

### ISSUE THREAD

**Issue by jason-roberts** [BrightstarDB/BrightstarDB#136]
Brightstar does not currently install into a phone 8.1 winrt project (it does install into a Windows Phone 8.1 Silverlight project).

Install output description below - looks like a downlevel dependency with dotNetRDF - I have added an issue with the project team there (http://www.dotnetrdf.org/tracker/Issues/IssueDetail.aspx?id=429)

PM> Install-Package BrightstarDB
Attempting to resolve dependency 'BrightstarDBLibs (= 1.7.1.0)'.
Attempting to resolve dependency 'dotNetRDF (≥ 1.0.6)'.
'BrightstarDB 1.7.1.0' already installed.
Adding 'dotNetRDF 1.0.6.3421' to App1.
Install-Package : Could not install package 'dotNetRDF 1.0.6.3421'. You are trying to install this package into a project that targets 'WindowsPhoneApp,Version=v8.1', but the package 
does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
At line:1 char:1
- Install-Package BrightstarDB
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
  - FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

PM>

**Comment by treitmaier** [comment]
Hi kal,
It looks like the dotNetRDF project is making [headway](http://sourceforge.net/p/dotnetrdf/mailman/message/33150538/) supporting WinRT, WP8.1. Would you consider reopening this issue once dotNetRDF start supporting WinRT. Are there any other upstream dependencies that you think will be problematic?

Regards,

Thomas

**Comment by jason-roberts** [comment]
Would be v cool at some point if all the bits come together to be able to use BrightstarDB in all Universal apps with win 10 - including app running on xbox ! :)

**Comment by kal** [comment]
That would be cool. IIRC when I tried there were some significant bits of functionality missing from the XBox PCL profile. It was a while ago but I think it was pretty much all the HTTP networking stack. If things have moved on it would be nice to really spread the cross-platform love!
