### ISSUE TITLE
Make transaction logging optional

### ISSUE THREAD

**Issue by kal** [BrightstarDB/BrightstarDB#151]
Allow an embedded connection to be created without transaction logging enabled. When logging is disabled do not collect or write any transaction logging information or update transaction log headers.

This approach would mean that it would be possible to have intermittent transaction logging so the transaction log may not cover all of the commit points in the store. Ensure that the code for traversing commit points and matching commits and transaction log doesn't get broken by this.

An alternative approach would be to have the transaction logging level specified when the store is created - if the store is created without transactionheaders.bs, then no txn logging occurs.

Perhaps a combination ? If transactionheaders.bs exists, default is to do logging, but can be disabled by connection string setting. If transactionheaders.bs does not exist default is to not log, but can be disabled by connection string setting.

**Comment by kal** [comment]
This is now implemented. There are several ways of making use of the feature:

1) In the app.config/web.config, the <brightstar> section now has an additional supported element 'transactionLogging'. If the 'enabled' attribute of this element has a value other than 'true', then transaction logging is disabled. e.g.
<brightstar> <transactionLogging enabled='false' /> </brightstar>

2) From code, it is now possible to pass a configuration options object into the BrightstarService.GetClient() method. This object has a property on it to control transaction logging.

3) Deleting the transactionheaders.bs file from a store directory will prevent any further transaction logging. Creating a new empty file calle transactionheaders.bs in a store's directory will enable transaction logging. It is recommended to delete the transactions.bs file at the same time as the transactionheaders.bs file when disabling logging, but it is not necessary - if logging is disabled and re-enabled by this method without deleting transactions.bs, new transaction data simply gets appended to the existing file (but note that without the old headers, there is no way to programmatically access the old transaction data)

**Comment by jvdonk** [comment]
Just for the record:

The code option, 2), with the configuration specification only works for Embedded stores, not for Rest stores.

It is obvious when writing the code because one need to specify an EmbeddedServicesConfiguration but for Rest clients there is only option 1) and 3).

**Comment by kal** [comment]
It is the server that is really in control of transaction logging. So from a REST client neither (1) wouldn't work anyway (that is, if your web app is configured to use a REST connection to a BrightstarDB server, adding the transactionLogging element would have no effect). Obviously (3) is all about having access to the store directory so its also a server-only thing.

**Comment by jvdonk** [comment]
But a 2) option with a new overload having a RestServiceConfiguration?
Or, a IBrightStarService.CreateStore overload with the option to turn transactionLogging off.

Maybe I don't understand it correctly but I thought the BrightstarService.GetClient() is there to get a entrypoint to Admin stuff. So if it is an Rest client to the server and there would be a hypothetically  RestServiceConfiguration option(with the transactionLogging set to false), when the client calls CreateStore, the store is created without the transactionheaders.bs.
