### ISSUE TITLE
How to reduce the file size of the stores?

### ISSUE THREAD

**Issue by hornms** [BrightstarDB/BrightstarDB#153]
My application parses and loads data from many files into my BrightstarDB store, performs complex analysis and conversion of the store data, then produces other outputs.  This is working well and I have a rich object model layered on the store's Data Objects (over 300 classes).  However, my users are complaining that the size of the store files are too large.  For example, I loaded about 30 MB of data stored in XML files into the BrightstarDB store which caused the store to be over 6 GIG.  Yes, everything in the XML files is converted to objects+attributes with many relationships between them, but is there anyway to make the physical file of the store to be more space-efficient? I know the triples use GUIDs which are quite large, maybe you have a version that just uses sequential IDs?  Any design or technology suggestions are welcome.

Thanks
Mike

**Comment by kal** [comment]
No further info received. Future plans include some work on optimising store sizes but these are tracked as separate issues.
