### ISSUE TITLE
Nullable enums not supported

### ISSUE THREAD

**Issue by kentcb** [BrightstarDB/BrightstarDB#167]
Entities with nullable enums result in an error when generating the entity context code. Since non-nullable enums (e.g. `DayOfWeek`) and nullable non-enums (e.g. `int?` or `DateTime?`) are supported, I was expecting nullable enums (`DayOfWeek?`) to also work.

Sample error message:

```
Running transformation: Invalid property: Namespace.IEntity.Property - the property type System.Nullable<System.DayOfWeek> is not supported by Entity Framework.
```

**Comment by kal** [comment]
I'll check into this - I thought it was supported and tested in our unit tests, but I must be mistaken.

**Comment by kal** [comment]
Hi Kent,

It turned out to be a problem with the way I was checking the type in a nullable property - it wasn't taking into account the possibility that the enum could by a system type. I've fixed this in the develop branch now.
