### ISSUE TITLE
Cannot build source

### ISSUE THREAD

**Issue by kentcb** [BrightstarDB/BrightstarDB#169]
Hi,

It's not currently possible to build after grabbing a fresh copy of the source:

```
The imported project "C:\Program Files (x86)\MSBuild\MSBuildCommunityTasks\MSBuild.Community.Tasks.Targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  Y:\Repository\BrightstarDB\common.proj
```

**Comment by kal** [comment]
Hi Kent,

You will need to install MSBuild Community Tasks - you can find an MSI installer at https://code.google.com/p/msbuildtasks/downloads/list. 

There is more on building BrightstarDB at http://brightstardb.readthedocs.org/en/latest/Building_BrightstarDB/ - if you spot any errors or omissions that trip you up when trying to build from source, please let me know!

Cheers

Kal

**Comment by kentcb** [comment]
Hi Kal,

My bad for not even *thinking* of consulting the docs for building.

However, there is a wider point to be made here: that of lowering the barrier to entry. When I was using MSBuild+Community Tasks in my OSS projects, I copied the binaries and target files into a *Lib* directory so that no installation was required. This made it possible to simply clone and build.

That said, I recently converted from MSBuild+Community Tasks to [FAKE](http://fsharp.github.io/FAKE/) and have found it to be vastly superior. [Here is an example](https://github.com/kentcb/KBCsv/blob/master/build.fsx) of one of my build scripts, which does everything from generating assembly/version metadata, unit testing, NuGet deployments, etc.

Do you think either of these options are worth considering for B*?

**Comment by kal** [comment]
I definitely think it would be worth making it as simple as possible to build B* from source. FAKE looks interesting - I hadn't come across that before. If it plays better with Mono then that would be a point in its favour - at the moment the build in a *nix environment is driven by a shell script. 

But even if we don't go down the FAKE route, including the CT binaries and targets in the B* source tree is a good intermediate step. 

I'll open another issue to track this.
