### ISSUE TITLE
Cannot update nullable property to null

### ISSUE THREAD

**Issue by kentcb** [BrightstarDB/BrightstarDB#170]
This is a blocking issue for me.

The following code:

```C#
[Entity]
public interface ITestEntity
{
    string Id
    {
        get;
    }

    int? Property
    {
        get;
        set;
    }
}

class Program
{
    static void Main(string[] args)
    {
        var connectionString = "type=embedded;storesdirectory=Stores;storename=Repro";
        var client = BrightstarService.GetClient(connectionString);

        if (client.DoesStoreExist("Repro"))
        {
            client.DeleteStore("Repro");
        }

        using (var context = new MyEntityContext(connectionString))
        {
            var entity = new TestEntity
            {
                Id = "id",
                Property = 10
            };

            context.TestEntities.Add(entity);
            context.SaveChanges();
        }

        using (var context = new MyEntityContext(connectionString))
        {
            var entity = new TestEntity
            {
                Id = "id",
                Property = null
            };

            entity.Context = context;
            context.SaveChanges();
        }

        using (var context = new MyEntityContext(connectionString))
        {
            var entity = context.TestEntities.Single();

            Console.WriteLine("Property Value: {0}", entity.Property);
        }

        Console.ReadKey();
    }
}
```
Outputs:
```
Property Value: 10
```

**Comment by kal** [comment]
Hi,
This is to do with the way you are doing the update. Instead of creating a new TestEntity instance with the same Id property value, try instead retrieving the entity and setting its property to null. Code like this (untested) should work in your second `using` block:
```c#
using (var context = new MyEntityContext(connectionString)) {
  var entity = context.TestEntities.FirstOrDefault(x=>x.Id == "id");
  entity.Property = null;
  context.SaveChanges();
}
```
This way the code "knows" that you are actually updating the property of an existing entity rather than redundanty setting the property of a new entity to its default value.

That should fix the problem - if it doesn't feel free to reopen this issue!

**Comment by kentcb** [comment]
Hi Kal,

The reason I was creating a new entity rather than retrieving the existing one has to do with my use case. I have some external code (add-ins, if you will) that provide my code with an entity (actually, they implement a contract and I have to convert that contract to an entity). Therefore, it made sense to me to just attach that entity to the context rather than looking it up and copying data from their entity to the resolved entity.

However, your comments pushed me in the right direction. I simply have to attach the context *before* setting the property to null. This works in as my second `using` block:
```C#
using (var context = new MyEntityContext(connectionString))
{
    var entity = new TestEntity
    {
        Id = "id"
    };

    entity.Context = context;

    entity.Property = null;
    context.SaveChanges();
}
```
But what confused me is the inconsistency with the treatment of `null` versus other values. For example, if I instead do this:
```C#
using (var context = new MyEntityContext(connectionString))
{
    var entity = new TestEntity
    {
        Id = "id",
        Property = 30
    };

    entity.Context = context;
    context.SaveChanges();
}
```
Then I *do* see `30` as the value! Since that was my starting point, I simply changed the `30` to `null` and expected it to work.
