### ISSUE TITLE
Simplify build process

### ISSUE THREAD

**Issue by kal** [BrightstarDB/BrightstarDB#172]
Followup from issue #169.

It would be good to reduce the friction in building B* from source. In particular the current build instructions require a separate download and installation of MSBuild Community Tasks.

Two suggested solutions for this:

1.  Include the CT binaries and targets in the B* source tree (e.g. under /tools).
2. Use [FAKE ](http://fsharp.github.io/FAKE/)

**Comment by kal** [comment]
FAKE didn't want to play nicely for me. So I've taken route (1) instead. I've also taken the opportunity to automate the installation of NUnit using NuGet and to make the build process work on Linux using Mono. Every thing can be built using `msbuild build.proj /t:Build` in Windows, and `xbuild build.proj /t:Build` in Linux. `msbuild build.proj /t:RunTests` runs the NUnit test suites, but currently the tests don't compile properly under Mono (due to some assembly signing issues that I need to look into).

I'm not to worried about fixing the test building under Mono right now, but I will need to update the docs before I close this issue.

**Comment by kal** [comment]
Docs updated.

**Comment by kentcb** [comment]
Hi Kal,

Do you recall what didn't work with FAKE? I was just about to start a PR based on #169 and then noticed your updates here.

**Comment by kal** [comment]
I don't recall exactly, but I think it was to do with running the NUnit tests. In any case I found it easier to use NuGet and tidy up the MSBuild/XBuild process than to get FAKE to do more than just building solutions.
