### ISSUE TITLE
1.9.1 breaks non-unified (x64) iOS apps

### ISSUE THREAD

**Issue by kentcb** [BrightstarDB/BrightstarDB#176]
Even though the Monotouch DLL is still shipped, the platform name itself has been removed from `PlatformAdapter`, so 1.9.1 effectively breaks non-unified iOS apps. Granted, one could manage the references manually, but I assume this was an unintentional break.

**Comment by kal** [comment]
Definitely unintentional and a bug!

**Comment by kal** [comment]
Fixed in a6b58ca0d0371dfe5feaed89a471fc61c5cbee8f
