### ISSUE TITLE
Should IEntitySet<T> be covariant for T?

### ISSUE THREAD

**Issue by kentcb** [BrightstarDB/BrightstarDB#179]
Something I noticed as I was getting up to speed on B*: `IEntitySet<T>` is not currently covariant on `T`. I couldn't see any reason why it shouldn't be and it made some things harder than they could otherwise have been, so wanted to raise as an issue.

**Comment by kal** [comment]
That would be really nice to do but unfortunately its not possible with the current definition of IEntitySet<T>. Because T is used both as a return type and a parameter type.
