### ISSUE TITLE
Why can't persistence type be specified via the connection string?

### ISSUE THREAD

**Issue by kentcb** [BrightstarDB/BrightstarDB#180]
My code relies on the automatic store creation behavior that occurs upon first accessing via a context. However, this seems to mean I have no choice about the persistence type. I actually want the re-writable type, but have no means of specifying that (iOS application).

It seemed logical to me to have an extra parameter in the connection string that allows the persistence type to be specified in case the store needs to be created, but maybe I'm missing something.

**Comment by kal** [comment]
You can set the default type in the configuration from your code:

```
Configuration.PeristenceType = PersistenceType.Rewrite;
```

Alternatively the iOS configuration provider does also read system settings from NSUserDefault.StandardUserDefaults (the key will be BrightstarDB.PersistenceType).

Will either of those work for you ?

**Comment by kentcb** [comment]
Ah, wasn't aware of that - thanks.
