### ISSUE TITLE
Collections don't maintain natural order

### ISSUE THREAD

**Issue by kentcb** [BrightstarDB/BrightstarDB#185]
Maybe this is intentional, but this certainly goes against my expectations. When creating an entity with a collection of child entities, the order of those child entities is not maintained.

Example code:
```C#
[Entity]
public interface IQuote
{
    string Id
    {
        get;
    }

    [InverseProperty("Quote")]
    ICollection<IQuoteItem> Items
    {
        get;
        set;
    }
}

[Entity]
public interface IQuoteItem
{
    string Id
    {
        get;
    }

    string Name
    {
        get;
        set;
    }

    IQuote Quote
    {
        get;
        set;
    }
}

using (var context = new MyEntityContext(connectionString))
{
    var quote = context.Quotes.Create();
    var item = context.QuoteItems.Create();
    item.Name = "First";
    quote.Items.Add(item);
    item = context.QuoteItems.Create();
    item.Name = "Second";
    quote.Items.Add(item);
    item = context.QuoteItems.Create();
    item.Name = "Third";
    quote.Items.Add(item);

    context.Quotes.Add(quote);
    context.SaveChanges();
}

using (var context = new MyEntityContext(connectionString))
{
    var quote = context
        .Quotes
        .FirstOrDefault();

    foreach (var item in quote.Items)
    {
        Console.WriteLine(item.Name);
    }
}

Console.WriteLine("DONE");
```
Output (changes run-to-run):
```
Second
First
Third
DONE
```
I was, of course, expecting them in order (first, second, third).

I guess this has to do with the underlying storage mechanism but I wanted to ask the question anyway. Obviously I could get around this by storing some other "order" property for each item, but that seems naff.

**Comment by kal** [comment]
Because BrightstarDB is built on top of RDF, it inherits RDF's lack of ordering. There are approaches to modelling ordered lists in RDF but they end up being heavy and hard to query. I think in general taking an application-specific approach to ordering (like adding an order property) is probably the way to go. It might be something to come back and revisit in 2.0 though.

**Comment by kentcb** [comment]
Fair enough - I suspected as much. I've just supplemented my entities with an `Index` property which I use to order them. Works fine and only the data layer "knows" about it.
