### ISSUE TITLE
AddOrUpdate for entity with composite key failing

### ISSUE THREAD

**Issue by kentcb** [BrightstarDB/BrightstarDB#194]
Following on from #192, the following code is also failing:
```C#
[Entity]
public interface IParentEntity
{
    [Identifier("http://example.org/repro/")]
    string Id
    {
        get;
    }

    [InverseProperty("Parent")]
    ICollection<IChildEntity> Children
    {
        get;
        set;
    }
}

[Entity]
public interface IChildEntity
{
    [Identifier("http://example.org/repro/", KeyProperties = new[] { "Parent", "Code" })]
    string Id
    {
        get;
    }

    string Code
    {
        get;
        set;
    }

    string Description
    {
        get;
        set;
    }

    IParentEntity Parent
    {
        get;
        set;
    }
}

using (var context = new MyEntityContext(connectionString))
{
    var parent = new ParentEntity();
    parent.Id = "parent";
    var child = context.ChildEntities.Create();
    child.Code = "child";
    child.Description = "Some description";
    child.Parent = parent;
    context.ChildEntities.Add(child);

    context.SaveChanges();
}

using (var context = new MyEntityContext(connectionString))
{
    var parent = context.ParentEntities.First();
    var modifiedChild = new ChildEntity
    {
        Parent = parent,
        Code = "child",
        Description = "A new description for the existing child"
    };

    var existingChild = context.ChildEntities.First();
    context.DeleteObject(existingChild);
    context.ChildEntities.Add(modifiedChild);
    context.SaveChanges();
}
```
I realize the update logic looks weird, but it's just a simulation for what's really happening in my actual project. The final call to `SaveChanges` fails with:
```
BrightstarDB.EntityFramework.UniqueConstraintViolationException was unhandled
Message: An unhandled exception of type 'BrightstarDB.EntityFramework.UniqueConstraintViolationException' occurred in BrightstarDB.dll
Additional information: One or more new resources have an identifier that conflicts with an existing resource of the same type.
```
Again, I am just trying to implement an `AddOrUpdate()` method, this time for an entity with a composite key. It seems that because I'm not obtaining the entities via the context (I really can't in my scenario), things are getting confused.

**Comment by kal** [comment]
Worth checking if this is still reproducible after the other fixes that were made to EF.

**Comment by kal** [comment]
This is reproducible still. I think it comes from the fact that (at least in the sample code) there is not an allowance made for the fact that the update will delete the entity and then add it again. When a generated key is used we check the unique constraint before applying the updates. I think the key here is to pre-process the update before sending it and not check the unique constraint for entities that are being deleted in the same transaction.

**Comment by kal** [comment]
Should be fixed now - I added repro tests based on your code above.
