### ISSUE TITLE
Libs NuGet package has third party DLLs in it

### ISSUE THREAD

**Issue by kentcb** [BrightstarDB/BrightstarDB#195]
The BrightstarDBLibs NuGet package includes a bunch of third party DLLs, including *Newtonsoft.Json.dll*. These should be declared as dependencies of the NuGet package rather than being bundled with B*. Otherwise, all sorts of issues can occur such as my reference to *Newtonsoft.Json.dll* being overwritten with B*'s older version when I upgrade B*.

**Comment by kal** [comment]
Actually that is deliberate, the third-party nugets do not (or at time of packaging did not) properly support the same profile as BrightstarDB so they had to be bundled otherwise the dependencies would not be correctly resolved.

**Comment by kentcb** [comment]
Is this still true though? Newtonsoft.Json appears to support just about every platform...

**Comment by kal** [comment]
It was the last time I checked which was the 1.9 release. I can retest this at the next release point. Nuget profile management does my head in!

**Comment by kal** [comment]
Recheck this before making the next release.

**Comment by kal** [comment]
It does look like Newtonsoft.Json 6.0.8 is happy to install into an iOS application. I'll remove that assembly from the lib and add a nuget dependency instead.
