### ISSUE TITLE
.Add failing if Id is not explicitly declared

### ISSUE THREAD

**Issue by jd78** [BrightstarDB/BrightstarDB#197]
Hello. Below the bug:

    [Entity]
    public interface IPrice
    {
        DateTime RecommendedAt { get; set; }
    }

    var price = new Price { .... }
    context.Prices.Add(price) ==> Throws a NullReferenceException.

    The problem is solved adding the Id to the interface:

    [Entity]
    public interface IPrice
    {
        string Id { get; }
        DateTime RecommendedAt { get; set; }
    }

    var price = new Price { .... }
    context.Prices.Add(price) ==> Correctly processed.

**Comment by kal** [comment]
Just pushed a fix for this. While testing I noticed that you would also get an error when trying to set a property of the entity with no ID using another entity, so I fixed that too. I may not have caught all the possible corner cases though. Let me know if you have any further problems with it.

**Comment by jd78** [comment]
Cheers. I'll let you know on Monday in case of further errors.
