### ISSUE TITLE
AssemblyInfo.cs file absent

### ISSUE THREAD

**Issue by kentcb** [BrightstarDB/BrightstarDB#201]
Just FYI, the *develop* branch has *AssemblyInfo.cs* inside the *Portable.iOS* project, but it does not exist:

![image](https://cloud.githubusercontent.com/assets/1901832/6342898/c3ed25e8-bc2f-11e4-893a-03e163068a53.png)

**Comment by kal** [comment]
Thanks for the heads up - was missing a BeforeBuild target in the .csproj for Portable.iOS and Portable.MonoTouch. Fixed now.
