### ISSUE TITLE
Poor feedback in Polaris when import fails

### ISSUE THREAD

**Issue by kal** [BrightstarDB/BrightstarDB#212]
User just sees "Job Error" - with no specific error details.

**Comment by Lercher** [comment]
The diagnostic information in Polaris and in the web UI is also very "reduced" on malformed sparql updates. Basically it only states that an error occurred. Probably this has the same cause. It would be great to see more detailed parser errors.

**Comment by kal** [comment]
Thanks @Lercher - will be sure to check that too.

**Comment by kal** [comment]
Testing this locally it looks like the importer provides detailed feedback when doing a remote import; but "reduced" feedback when doing a local import.

**Comment by kal** [comment]
I think I've caught all the different branches that were under-reporting error messages. Let me know if you find any others.
