### ISSUE TITLE
Support for Windows 10 Universal Application Platform (UAP)

### ISSUE THREAD

**Issue by fgoulet** [BrightstarDB/BrightstarDB#237]
I would really like to give a try to BrightstarDB in my Windows 10 store app.

**Comment by CrafttDev** [comment]
I would like to second this request for Windows 10 support I have been looking for a replacement for SQLite.

**Comment by kal** [comment]
@CrafttDev, @fgoulet - I hear you guys. I'll see what I can do!

**Comment by ShiroYacha** [comment]
Yeah this can really be helpful! But I assume that for now, we can still implement the PCL and leave the storage later when the UWP support comes up?

**Comment by kal** [comment]
Yeah I think you can - there are some API differences which will bite you when you are ready to convert the project over to UWP, but from the work I've done so far on porting dotNetRDF over to .NET Core it seems that they aren't to hard to work around.

**Comment by kal** [comment]
Further comment on this as I've looked into it a bit more. As far as I can see from the testing I have done so far, the PCL version of BrightstarDB will work just fine for a Windows Store 10 app (at least I have managed to use it to compile a very simple app that uses BrightstarDB). 

I feel that for now this is "good enough". Ideally I think we need to get to the point of supporting some flavour(s) of .NET Core - this would work for UWP apps as well as DNX and mono. I'm not sure of exactly when this would get done as I think it also requires a discussion with Rob and the other dotNetRDF developers about their plans.

So, I'm going to close this issue as a Wont Fix. 

However, if anyone disagrees with my evaluation or if you find that actually you do have an issue getting the PCL version of B* running with your Windows 10 app, please feel free to open another issue but please be as specific as possible about what you are trying to achieve and what the problem appears to be.
