### ISSUE TITLE
Roslyn Nuget Packages Broken

### ISSUE THREAD

**Issue by jlind0** [BrightstarDB/BrightstarDB#239]
The T4 Template won't even install because nuget is unable to find a dependency. The console package does not install a .exe to run from the command line.

**Comment by kal** [comment]
Thanks for the report - can you let me know a bit about your environment - especially:

 * The version of Windows you are running (or if you are on OS X/Linux which version of Mono you are using)
 * The version(s) of Visual Studio you have installed (if any)
 * The target framework for the project that you are installing the NuGet package into

Also, if you got any more detailed error message either from NuGet or from the T4 template that might help me out too.

**Comment by jlind0** [comment]
Windows Server 2016, .NET 4.6, Visual Studio 2015 professional. I ended up downloading the source and manually built the T4 project and copied the output to my solution and referenced the dll's. The tool runs successfully after I do that.

Sent from my Windows Phone
________________________________

**Comment by kal** [comment]
Great, thanks for the information. It sounds like its possibly a packaging issue then - the T4 template should be trying to find the assemblies in the tools directory created under the nuget package directory, but perhaps that is failing.

**Comment by jlind0** [comment]
It looks like for T4 the underlying dependency CodeGen package is marked but not deployed to nuget. Also i noticed there's a dependency on Humanizer but that's not marked in the T4 package, although that might be a dependency on CodeGen (i didn't look). The console package does not have any dependencies.

Sent from my Windows Phone
________________________________

**Comment by kal** [comment]
I found the problem in the packaging scripts that led to me failing to spot the missing dependency. 

The console package should install the executable (you would find it in packages\BrightstarDB.CodeGeneration.Console.1.11.0.0\tools) but perhaps there was an issue with that package?

**Comment by kal** [comment]
I've tested this with the official 1.11.1 packages from NuGet and it works fine for me. If you have any further problems please open a new issue!
