### ISSUE TITLE
Update the documentation around how to create and use the Brightstar Entity Context

### ISSUE THREAD

**Issue by jvdonk** [BrightstarDB/BrightstarDB#245]
Following the instructions from the Developer Quick Start, there are no 'Add New Item -> 'Brightstar Entity Context' or 'Brightstar Entity Context' items. This is in a Windows 10 x64, Visual Studio 2015 Professional environment.

The Brightstar CodeGeneration.* nuget packages suggest that there are other options to generate such a Entity Context but there is, or I can't find it, documentation on how to use those to generate Entity Contexts(or definitions, but those are easily crafted by hand with the Entity-attribute).

The BrightstarEntityContext.vsi from the install-dir isn't working either to add the menu items. It doesn't seem compatible with Visual Studio 2015 anymore?

What is the preferred method to generate Entity Contexts?

**Comment by kal** [comment]
The currently packaged VSI / Windows installer don't yet support VS2015.

The preferred way to add a BrightstarDB Entity Context to a project is to use NuGet and add the BrightstarDB NuGet package - this will add an entity context text template generator to your project. If you would prefer to use the Roslyn generator then the package to install is BrightstarDB.CodeGeneration.T4 - this will also add a text template file, but this template is just a convenience wrapper that invokes the Roslyn code generator when the template is executed.

With either of these packages, all the additional required dependencies should get installed by NuGet automatically; and you can rename the .tt file to change both its name and the name of the generated entity context class.

In terms of adding a new entity I'm afraid that right now the only way is to code that by hand, but as you have noted the "New Brightstar Entity" template is really pretty trivial and easy enough to code by hand.

I'm going to leave this issue open as a reminder to me to update the documentation for 1.12.
