### ISSUE TITLE
Not all child entities are deleted

### ISSUE THREAD

**Issue by jvdonk** [BrightstarDB/BrightstarDB#246]
I'm trying to create a store for collecting synchronization data with a maximum number of synchronizations, say 10. So when a synchronization of data occurs it is saved(with its data) in the store and when the total number of synchronizations exceeds the maximum, the oldest ones are deleted.

This partially works, the oldest synchronizations are deleted but not all of it's child data, some, but not all.

This is my setup:

```
A collection of Synchronizations(ISynchronisatie)
  a ISynchronisatie has a collection of Debiteuren(IDebiteur)
    a IDebiteur has a single CorrespondentieAdres(IAdres)
    a IDebiteur has a collection of VerzendAdressen(IAdres)
  a ISynchronisatie has a collection of Crediteuren(ICrediteur)
    a ICrediteur has a single CorrespondentieAdres(IAdres)
    a ICrediteur has a collection of VerzendAdressen(IAdres)
```

When I delete the oldest ISynchronisatie objects(see code below) its child IDebiteur and ICrediteur objects are deleted as well(that's good). But not the child collection elements(IAdres) of the IDebiteur/ICrediteur elements itself. I verify the numbers with the Polaris tool, in the Statistics page.

So the pile of IAdres objects(triples) keeps growing. This is just a initial setup of data, the number of child collections will expand much more and thus the total number of objects that aren't deleted as well.

So, what can I do to get the corresponding child elements to be removed as well when I delete a ISynchronisatie object.

My code:

in AssemblyInfo.cs:
```
[assembly: TypeIdentifierPrefix("http://sample.com/types/")]
[assembly: NamespaceDeclaration("sample", "http://sample.com/")]
```

Entitties:
```
[Entity("sample:Synchronisatie")]
public interface ISynchronisatie {

  [Identifier("sample:synchronisaties/")]
  string Id { get; }

  DateTime Timestamp { get; set; }

  ICollection<IDebiteur> Debiteuren { get; set; }

  ICollection<ICrediteur> Crediteuren { get; set; }
}

[Entity("sample:Debiteur")]
public interface IDebiteur {

  [Identifier("sample:debiteuren/")]
  string Id { get; }

  int Nummer { get; set; }

  string Zoekcode { get; set; }

  string Naam1 { get; set; }

  string Naam2 { get; set; }

  string Straat { get; set; }

  string Huisnummer { get; set; }

  ICollection<IAdres> VerzendAdressen { get; set; }

  IAdres CorrespondentieAdres { get; set; }
}

[Entity("sample:Crediteur")]
public interface ICrediteur {

  [Identifier("sample:crediteuren/")]
  string Id { get; }

  int Nummer { get; set; }

  string Zoekcode { get; set; }

  string Naam1 { get; set; }

  string Naam2 { get; set; }

  string Straat { get; set; }

  string Huisnummer { get; set; }

  ICollection<IAdres> VerzendAdressen { get; set; }

  IAdres CorrespondentieAdres { get; set; }
}

[Entity("sample:Adres")]
public interface IAdres {

  [Identifier("sample:adressen/")]
  string Id { get; }

  string Naam1 { get; set; }

  string Naam2 { get; set; }

  string Straat { get; set; }

  string Huisnummer { get; set; }
}

```

Code for creating a synchronisation(with sample data):

```
using (var context = new MyContext(@"Type=rest;endpoint=http://localhost:8090/brightstar;StoreName=MyStore")) {

  var synchronisatie = context.Synchronisaties.Create();
  synchronisatie.Timestamp = DateTime.Now;

  IDebiteur deb = null;
  ICrediteur cred = null;
  IAdres adres = null;
  for (int i = 1; i <= 1000; i++) {
    deb = context.Debiteurs.Create();
    deb.Nummer = i;
    deb.Zoekcode = String.Format("DEB{0}", i);
    deb.Naam1 = String.Format("Naam debiteur {0}", i);

    adres = context.Adress.Create();
    adres.Naam1 = String.Format("NaamCorrespondentie deb {0}", i);
    deb.CorrespondentieAdres = adres;

    for (int c = 1; c <= 2; c++) {
      adres = context.Adress.Create();
      adres.Naam1 = String.Format("NaamVerzendAdres deb {0} adres {1}", i, c);

      deb.VerzendAdressen.Add(adres);
    }

    synchronisatie.Debiteuren.Add(deb);
  }

  for (int i = 1; i <= 1000; i++) {
    cred = context.Crediteurs.Create();
    cred.Nummer = i;
    cred.Zoekcode = String.Format("CRED{0}", i);
    cred.Naam1 = String.Format("Naam crediteur {0}", i);

    adres = context.Adress.Create();
    adres.Naam1 = String.Format("NaamCorrespondentie cred {0}", i);
    cred.CorrespondentieAdres = adres;

    for (int c = 1; c <= 2; c++) {
        adres = context.Adress.Create();
        adres.Naam1 = String.Format("NaamVerzendAdres cred {0} adres {1}", i, c);

        cred.VerzendAdressen.Add(adres);
    }

    synchronisatie.Crediteuren.Add(cred);
  }
  context.Synchronisaties.Add(synchronisatie);
  
  context.SaveChanges();
}
```

Code for cleaning up old Synchronizations:

```
using (var context = new MyContext(@"Type=rest;endpoint=http://localhost:8090/brightstar;StoreName=MyStore")) {

  foreach (var sync in context.Synchronisaties.OrderByDescending(s => s.Timestamp).Skip(5).ToList()) {
    context.DeleteObject(sync);
  }
  context.SaveChanges();
}
```

**Comment by jvdonk** [comment]
So, below is an overview of the Statistics page where the sample synchronization has been run 12 times, before the cleanup:

![image](https://cloud.githubusercontent.com/assets/1164988/11089217/7b6f8abc-8868-11e5-926a-56a938cc3b67.png)


And after the cleanup, keeping only the 5 newest synchronizations:

![image](https://cloud.githubusercontent.com/assets/1164988/11089269/c5989eee-8868-11e5-96ff-0e5dc136a6a1.png)

**Comment by kal** [comment]
Hi,

Actually BrightstarDB won't delete any connected entities. B* has no concept of entity containment as it works in a graph. The stats you are looking at are showing the counts of predicates - that is the count of properties in the database, not of the entities. So in fact your Crediteuren and Debiteuren entities are also still there ! It is just the properties that connected them to the deleted Synchronisatie instances that have gone.

I realize that is probably not want you wanted to hear :) I think the best way to handle this case - where you have some application-specific rules about the containment of entities - would be to implement a Delete method on the entity itself in an extension class. That method would iterate through all the "child" entities and delete them (possibly by calling a Delete method on them) and so on down the cascade.

It would be nice to have some sort of built-in support for this. For example we could add a specific decorator to properties that are to be considered as "contained" in the parent entity and that should take part in a cascading delete - and perhaps that could be implemented as a method separate from the Delete method on the context or maybe by overriding the Delete method to accept a "cascade" parameter. 

Unfortunately my time is a bit short at the moment, but if someone comes up with a nice way to do a more generic "cascading delete" for the B* entity framework I would be more than happy to review a PR ! See issue #247 which I've created to track this as an enhancement request.

**Comment by jvdonk** [comment]
So the ISynchronisatie objects are indeed deleted, except for the 5 most recent ofcourse, and the child elements have to be deleted explicitly by its containing object.

Once that is implemented there won't be any orphaned objects filling up the store?

I'll give it a try, thanks!
