### ISSUE TITLE
Windows Phone 8.1

### ISSUE THREAD

**Issue by jamescoffman23** [BrightstarDB/BrightstarDB#248]
I am trying to see if this would be a good fit for a Windows Phone 8.1 project but I cant seem to get it working correctly. 

I created a blank windows phone project in VS 2015, used nuget to pull in brightstar 1.11.1 including the platform package.  Created a model and was able to insert a record. Everything is fine until i try to query. 

I get an exception: 'System.IO.FileNotFoundException' in dotNetRDF.DLL. 
Could not load file or assembly 'VDS.Common, Version=1.6.0.0, Culture=neutral, PublicKeyToken=ab5f4eb908061bf0' or one of its dependencies. The system cannot find the file specified.

I referenced VDS.Common dll from the BrightstarDb SDK folder but it is looking for: Could not load file or assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.

I am missing a step somewhere.

**Comment by kal** [comment]
Hi,

It sounds like there may be a problem with dependencies with .NET Core - right now DotNetRDF and BrightstarDB don't have specific builds for .NET Core and CoreFX, but NuGet seems to just stuff the libraries in your project and hope that the .NET Core platform can cope! I would like to get B* running properly on NET Core; but that may take a bit of time as it sounds like the problems really hit with the upstream dependencies.

This is the point at which I say that if you have experience with dealing with .NET Core then any assistance or pointers would be most welcome - as I have to say it all confuses me!

It's a bit difficult to be sure without seeing the specifics of your application; but it might be worth trying instead to build a cross-platform mobile app solution instead. You can always delete the Android and iOS parts of the solution! The solution template can be found (at least on my VS2015 installation) under Visual C# > MobileApps > BlankApp (Native Portable). This builds with the Xamarin tools (for iOS and Android) and it avoids .NET Core. If you don't see it in your VS installation you may need to install some of the optional bits of VS (it comes with VS 2015 Professional and up I believe).

Cheers

Kal

**Comment by jamescoffman23** [comment]
Hi, Kal,

 

I didn’t have much time to really dig into this but I tried do what you suggested with the cross platform solution but I couldn’t get it to compile with this: 

 


Severity

Code

Description

Project

File

Line


Error

 

Cannot find type System.Security.Cryptography.HashAlgorithm in module dotNetRDF.dll.

App3.WinPhone
