### ISSUE TITLE
Embedded store on OneDrive/GoogleDrive/...

### ISSUE THREAD

**Issue by ShiroYacha** [BrightstarDB/BrightstarDB#251]
Hi,
I would like to know if it is possible to **create** and **access** a store on shared cloud storage services such as OneDrive, GoogleDrive, etc. from a UWP(when it's supported)/WinRT application. 

My understanding is that the storage units are files, so in the worst case I can always upload/download files from the application local folder to cloud folder (vice versa) and access them locally? But is there a way to create and access the store directly on a remote folder?

**Comment by kal** [comment]
Hi,

Currently no there isn't a way to do that. However data access is reasonably abstracted so it may be possible to implement something if someone is interested in doing it. 

Syncing a folder might work, the only trouble is that you could possibly end up with the main data.bs and the master.bs files getting out of sync - that might not be too much of a problem if you are using an append-only store (although you could possibly lose a transaction), but would be a problem if you are using the rewrite store.

Another possibility might be to use the facility in B* to do a store snapshot - this is a compressed copy of the store that can be created in another folder. You can configure B* to take snapshots every N transactions or M minutes - maybe you could use this as a means of syncing from a master server to slave servers.

If you get a chance to play with something, let us know!

Cheers

Kal

**Comment by kal** [comment]
I'm going to mark this as a question and close it. If more people would like to have this feature and there is a volunteer to take it on; then I'd be happy to open an enhancement ticket.
