### ISSUE TITLE
Make blank node by BrightstarDB data object layer

### ISSUE THREAD

**Issue by KamalAlipour** [BrightstarDB/BrightstarDB#255]
Hi, I'm looking for blank node making by BrightstarDB. I can't find it in this link:
http://brightstardb.readthedocs.org/en/latest/Data_Object_Layer/
I would appreciate any help.

Thanks for your advice

Kind regards
Kamal

**Comment by kal** [comment]
Hi,

BrightstarDB doesn't store blank nodes - we always skolemize them. You can import an RDF file containing blank nodes, and the blank nodes will be converted to IRIs.

I'm interested - do you have a particular use-case for retaining blank nodes ?

Cheers

Kal

**Comment by KamalAlipour** [comment]
HI Kal,
I appreciate all your valuable advices. So if I got it right, I should generate unique IRIs automatically, or maybe BrightstarDB can do it for me because I need to have these IRI in my ontology where links a news to a collection of factors which is no name and all must be unique.

Thanks for your advice

Best regards
Kamal
