### ISSUE TITLE
Different interface/entity access level

### ISSUE THREAD

**Issue by nickdodd79** [BrightstarDB/BrightstarDB#260]
Hi,

With the EF approach, is it possible to to have a different access level for the entity interface and the generated entity class, without manually altering the T4 template?

So just to elaborate, I want to make my interfaces public so anything outside the data project can consume them. However the concretes I would like to keep internal and prevent access to create instances of them. At the moment. what ever I set my interfaces to, the classes take on.

Thanks,

Nick.

**Comment by kal** [comment]
Hi Nick,

Currently this isn't possible, but it is a really good idea. Right now, creating an public interface for the entity definition results in a public implementation class. 

It seems to me like this would be something that could be controlled using an additional custom attribute to control the default visibility of the generated classes. I'm thinking that it would make most sense for this to be another assembly-level custom attribute (like the [NamespaceDeclarationAttribute](http://brightstardb.readthedocs.org/en/latest/Entity_Framework/#namespace-declaration-attribute)). It could also be an interface-level custom attribute allowing you to control on a per-entity basis, but I'm not sure if there is a good reason for adding that additional level of complexity?

It feels like it should be pretty easy to do so I'll put this in as a feature for 1.13.

Cheers

Kal

**Comment by nickdodd79** [comment]
Awesome. 

Also, as a side note, there is a slight typo in one of the error messages generated for the EF stuff.

The property 'Id' must not have a setter to be used as the identity property for an entity. If this property is intended to be the identity property for the entity please remove the setter. If it is not intended to be the identity property, either rename this property or create an identity propertyn and decorate it with the [Identifier] attribute.

The second instance of 'property' in the last sentence has a rogue 'n' on the end.

**Comment by kal** [comment]
Thanks! I've fixed the typo and I'll take a look at implementing the attribute-based solution.

**Comment by kal** [comment]
Implemented now in the develop branch for both the T4 template and the Roslyn-based generators. Instead of using an assembly attribute, the flag to control this is in the T4 template itself (near the top and marked with a comment) - this makes more sense as it is really a compile-time setting rather than a runtime setting.

**Comment by nickdodd79** [comment]
Perfect. I'll give it a whirl.
