### ISSUE TITLE
Unable to install the Entity Context templates in Visual Studio 2015 Update 1 Community

### ISSUE THREAD

**Issue by LSMetag** [BrightstarDB/BrightstarDB#265]
Hi,

When I try to install the "BrightStarEntityContext.vsi", I get an error :

"Installation arrêtée, car le répertoire correspondant à la valeur ProjectType n'existe pas. Le type de projet n'est pas valide pour votre installation de Visual Studio."

Translated in english :

"Installation stopped, because the directory corresponding to the value ProjectType doesn't exist. The project type is not valid for your Visual Studio installation."

Nothing is installed.

**Comment by kal** [comment]
Hi,

The VSI was developed for VS2013  and it doesn't work in VS2015 at all I'm afraid :(
To be honest there isn't a lot in there - just the T4 template for BrightstarDB Entity Framework and a simple starter file for creating an entity interface. It is probably easier right now to just use NuGet to install the BrightstarDB package - this includes the T4 template and the interfaces are trivial to code by hand.

I'm going to take a look at creating a VSIX for VS2015 to reinstate this feature in a future release.

Cheers

Kal

**Comment by kal** [comment]
I've created a VSIX for this and added it to the installer. It will be part of the 1.13 release which should be ready to go either at the end of this week or beginning of next.
