### ISSUE TITLE
DataObjectLayer documentation out-dated

### ISSUE THREAD

**Issue by seveves** [BrightstarDB/BrightstarDB#283]
At http://brightstardb.readthedocs.io/en/latest/Data_Object_Layer/#querying-data-using-sparql you say that the "sparqlResult" has a "ResultDocument" property but I cannot find this property in the repository.
I did something like that as a workaround:

`var queryResult = DataObjectStore.ExecuteSparql(query);`
`foreach (var sparqlResultRow in sparqlResult.ResultSet)
{
    var val = sparqlResultRow["skill"].AsValuedNode().AsString();
    Console.WriteLine("Skill is " + val);
};`

**Comment by kal** [comment]
Thanks for the bug report! I've fixed up the documentation and the new version is now on readthedocs.

Cheers

Kal
