### ISSUE TITLE
Scalability for a social network

### ISSUE THREAD

**Issue by scy0846** [BrightstarDB/BrightstarDB#287]
I apologize for really throwing this in issues, but I mostly was trying to find out if this would handle the amount of scalability that one would expect in a social network. I would need it to be able to handle a very large amount of concurrent users(1 million or more). I was initially going to go with MongoDB, but your DB has everything that I really want for the database, but I'm curious if you think it would work to almost the same scale as MongoDB or not. Thank you for your answer and I really look forward to it. I'm watching this project because I would love to see this in use on a large scale.

**Comment by kal** [comment]
I would say that right now B* is not suitable for this scale of application. We would need a lot more work on the indexing and some support for horizontal scaling. Both of these are things I would like to tackle at some point, but realistically that isn't going to happen in a short time frame.
