### ISSUE TITLE
collection of literals not being saved

### ISSUE THREAD

**Issue by cjochoa** [BrightstarDB/BrightstarDB#294]
Hi, I have a class like

    [Entity]
    public interface IPerson
    {
        string Name{ get; set; }
        ...
        ICollection<string> Emails { get; } 
    }

When creating a Person, all properties are correctly persisted except for Emails, which is not persisted. Is there a restriction on this sort of collections? Is there any workaround? Should I create a dummy Email class and convert ICollection<string> to ICollection<Email>?

**Comment by osc117** [comment]
Is there any reason for your email collection to not have any setter ?

**Comment by cjochoa** [comment]
Sorry, forgot to add the setter in the example. The actual example has a setter anyways

**Comment by osc117** [comment]
Well if you have the setter and you did "Right click => Run Custom Tool" on your context.tt, your collection should be persisted without any problem

**Comment by cjochoa** [comment]
Weird, that is not happening. I isolated the code in https://github.com/cjochoa/rdfStore in case you want to give it a try. 
For me it is writing "PERSON name: John Doe emails:[]"
Thanks!

**Comment by cjochoa** [comment]
@osc117   I just found that doing this works

            var emails = new List<string>() { "john@a.com", "doe@b.com" };
            var person1 = context.Persons.Create();
            person1.Name = "John Doe";
            person1.Emails = emails;
            context.SaveChanges();

but this does not

            var person2 = new Person();
            person2.Name = "Jane Doe";
            person2.Emails = emails;
            context.Persons.Add(person2);

Printing will give me 

PERSON name: Jane Doe emails:[]
PERSON name: John Doe emails:[john@a.com,doe@b.com]

Will stick to the first method then,but I would like to understand why the second does not work in the same way

**Comment by osc117** [comment]
Okay i see your problem : 
`var person1 = context.Persons.Create(); // this is a way of instantiating  entities`
VS
`var person2 = new Person(); //this wont work`

**Comment by cjochoa** [comment]
@osc117  I am closing the issue since it is no longer an issue, but the [documentation](http://brightstardb.readthedocs.io/en/latest/Entity_Framework/#using-a-context) says this is a way of creating an entity too. Can you enlighten me on why does not work? And thanks a bunch for your help!

```
// or created using new and attached to the context
var bob = new Person() { Name = "Bob" };
dataContext.Persons.Add(bob);
```

**Comment by osc117** [comment]
Well i'm not an expert, but as far as i know i never achieved to persit data when instanciating directly an entity.
So either the documentation is wrong, either we are both missing something

**Comment by cjochoa** [comment]
Good to know, thanks!
