### ISSUE TITLE
Is BrightstarDB still alive?

### ISSUE THREAD

**Issue by charbull** [BrightstarDB/BrightstarDB#296]
Hello,

I was looking for EF with RDF and ended up here.
Very interesting project, is it still is supported?

Cheers

**Comment by kal** [comment]
To quote Monty Python, "Its not dead, just resting" :-)

I'm busy with a bunch of other projects at the moment (not least of which is dotNetRDF which is a major upstream dependency for B*) and without other major contributors to this project its not going to move forwards quite as fast as I had hoped. However, I still plan to come back to this project and update it as soon as I have got dotNetRDF sorted out a bit.

**Comment by charbull** [comment]
thank you for your reply ! Good luck and hope the resting of B* will be short :)
