### ISSUE TITLE
Any plans to support TinkerPop?

### ISSUE THREAD

**Issue by dfirka** [BrightstarDB/BrightstarDB#300]
Sorry dont know if this is the proper channel to ask.

We are evaluating different options, and would like to know if there are plans to support Gremlin as a query language.

Thanks
dan

**Comment by kal** [comment]
Hi Dan,

No plans to support Gremlin. Gremlin is really aimed at Property Graph databases and BrightstarDB is an RDF triple store so I'm not sure exactly how well Gremlin would fit. 

Cheers

Kal
